### ISSUE TITLE
Cannot set property 'warmUp' of undefined

### ISSUE THREAD

**Issue by alan-cooney** [FidelLimited/serverless-plugin-warmup#175]
I'm getting the following error:

`{
  "errorType": "TypeError",
  "errorMessage": "Cannot set property 'warmUp' of undefined",
  "trace": [
    "TypeError: Cannot set property 'warmUp' of undefined",
    "    at Module.<anonymous> (/var/task/_warmup/webpack:/_warmup/index.js:9:1)",
    "    at Module.module.exports (/var/task/_warmup/index.js:146:30)",
    "    at __webpack_require__ (/var/task/_warmup/webpack:/webpack/bootstrap:19:1)",
    "    at /var/task/_warmup/webpack:/webpack/bootstrap:83:1",
    "    at Object.<anonymous> (/var/task/_warmup/index.js:87:10)",
    "    at Module._compile (internal/modules/cjs/loader.js:776:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)"
  ]
}`

Any ideas? It's proving challenging to debug.

**Comment by juanjoDiaz** [comment]
Sorry for the silence. Holidays got on the way.

The problem seems that `module.exports` is not defined in the webpack generated handler.

It might be a problem of how you are configuring webpack.
But I think that Webpack shouldn't be processing the warmup handler.
Probably just adding the warmup plugin after the webpack plugin solves the issue.

**Comment by juanjoDiaz** [comment]
Closing since there hasn't been any response.
Feel free to reopen if there is anything left to resolve.

**Comment by monsagri** [comment]
We're running into the same issue at the moment, warmup-plugin is added after the webpack plugin.

`
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
`

I agree that it seems like it would be a webpack issue, do you have any suggestions apart from changing the order? (which seems to not be fixing it for me)

**Comment by monsagri** [comment]
As a reference for anyone else running into this. 

We recently upgraded our node runtime to 10.15 and in the process our babelrc lost the commonjs module. Adding it back in fixed things.

**Comment by alan-cooney** [comment]
@monsagri thanks - can you confirm which commonjs module you are using, and/or show the relevant part of your babelrc?

**Comment by monsagri** [comment]
Sure!

.babelrc

```
{
  "plugins": ["source-map-support", "@babel/plugin-transform-runtime", "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread"],
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": "commonjs",
        "targets": {
          "node": "10.15"
        }
      }
    ]
  ]
}
```

Somehow during migration the modules block got lost, after adding it back into the .babelrc all is well.

**Comment by jaynakus** [comment]
This problem still exists. The plugin is incompatible with serverless-bundle or serverless-webpack in such cases when your code is written with es6 (imports instead of require). If you specify modules: "commonjs" dynamic imports are failing.

**Comment by juanjoDiaz** [comment]
Hi @jaynakus,

Can you provide a repo that I can use to reproduce this issue?

The warmers created by warmup plugin are packaged individually and don't need transpilation. So it you declare the warmup plugin after the webpack/bundle plugin, it should work.
If it doesn't, there might be some inconsistency on how different plugins use the lifecycles hooks. But I need a test project to reproduce the issue and validate a possible solution.

**Comment by jaynakus** [comment]
Here is the repo https://github.com/jaynakus/warmup

I could not share real project since it is private. Copied configuration to new repo. Did not try to deploy to AWS. 

In this setup main lambda will run properly but warmer lambda will fail. If I put `"modules":"commonjs"` in `.babelrc` file. This time the warmer lambda will work but main lambda will fail.

I hope you can reproduce since I didn't test on AWS this new repo.

**Comment by zanemountcastle** [comment]
I had the same issue using `serverless-bundle`.

**Comment by juanjoDiaz** [comment]
Fixed in version 5.2.0

Thank you for the repo!

**Comment by jaynakus** [comment]
I feel sorry to tell you that, with new version now the deployment to AWS is showing an error,
Same configuration with previous version deploys successfully 
 
```
  Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [WarmUpPluginDayLogGroup] in the Resources block of the template
      at /node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
      at runNextTicks (internal/process/task_queues.js:62:5)
      at processImmediate (internal/timers.js:429:9)
```

**Comment by juanjoDiaz** [comment]
Solved in v5.2.1
Sorry about the mess.

**Comment by juanjoDiaz** [comment]
Btw, I had to implement an ugly workaround for this. The proper solution is for the serverless-webpack plugin (bundle uses that under the hood) to finally implement https://github.com/serverless-heaven/serverless-webpack/issues/255 which have been sitting there for 4 years...

**Comment by jaynakus** [comment]
Thanks now it is working as expected !

**Comment by juztinlazaro** [comment]
Hi we are still encountering this issue `"serverless-plugin-warmup": "5.3.1",`
